name: MATLAB Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install XVFB
        run: sudo apt-get install xvfb
        
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        
      - name: Run MATLAB
        run: xvfb-run -a matlab -batch 'connector.internal.startConnectionProfile("loopbackHttps"); com.mathworks.matlabserver.connector.api.Connector.ensureServiceOn(); path = export("sample.mlx", Format="html")'
        
      - uses: actions/upload-artifact@v3
        with:
          name: sample-html
          path: sample.html
