name: MATLAB Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Start display server
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
        
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        
#       - name: Run MATLAB command
#         uses: matlab-actions/run-command@v1
#         with:
#           command: |
#             connector.internal.startConnectionProfile("loopbackHttps");
#             com.mathworks.matlabserver.connector.api.Connector.ensureServiceOn();
#             export("sample.mlx");
            
      - run: matlab -display :99 -batch "addpath(fullfile(matlabroot,'examples','matlab','main')); runtests"
        
      - uses: actions/upload-artifact@v3
        with:
          path: sample.pdf
